# Generated by Django 5.2.4 on 2025-11-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='predicted_price',
            field=models.FloatField(blank=True, help_text='Predicted price of the property', null=True),
        ),
    ]
