# Generated by Django 5.2.4 on 2025-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(help_text='Area of the property in square feet')),
                ('bedrooms', models.IntegerField(help_text='Number of bedrooms')),
                ('bathrooms', models.IntegerField(blank=True, help_text='Number of bathrooms', null=True)),
                ('stories', models.IntegerField(blank=True, help_text='Number of stories', null=True)),
                ('mainroad', models.BooleanField(blank=True, help_text='Is the property near a main road?', null=True)),
                ('guestroom', models.BooleanField(blank=True, help_text='Does the property have a guest room?', null=True)),
                ('basement', models.BooleanField(blank=True, help_text='Does the property have a basement?', null=True)),
                ('hotwaterheating', models.BooleanField(blank=True, help_text='Does the property have hot water heating?', null=True)),
                ('airconditioning', models.BooleanField(blank=True, help_text='Does the property have air conditioning?', null=True)),
                ('prefarea', models.BooleanField(blank=True, help_text='Is the property in a preferred area?', null=True)),
                ('furnishingstatus', models.CharField(blank=True, help_text='Furnishing status of the property', null=True)),
            ],
        ),
    ]
